---
ID: "e0186933-cab1-53f7-8b80-f3419e2d8c09"
Parent: "f17fb8e4-19cf-54b1-9afc-c0bd8edd79b4"
Template: "f17fb8e4-19cf-54b1-9afc-c0bd8edd79b4"
Path: "/sitecore/templates/Project/app/Styleguide-FieldUsage-Number/__Standard Values"
DB: master
SharedFields:
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{6C59AE29-D0A1-4B77-9305-0ABAB21D5FE5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190813T133636Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
