---
ID: "34f87564-3127-433a-a543-6fbc458c461e"
Parent: "c626493f-1cc3-4986-a701-f28b83d649f7"
Template: "814c1dbb-b118-4511-ba2b-7288ed3d490b"
Path: /sitecore/system/Modules/Layout Service/Rendering Contents Resolvers/Products Resolver
DB: master
SharedFields:
- ID: "de218ede-a9ad-4b04-86c5-9ff593ccf39d"
  Hint: Type
  Value: Jss.Commerce.ContentResolvers.ProductsContentResolver, Jss.Commerce
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190905T115356Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
