---
ID: "4c01fb8a-1eb8-5ce6-af9c-f5ba07294c36"
Parent: "fce19804-555e-5ba1-92a4-eedb3e1794d9"
Template: "fce19804-555e-5ba1-92a4-eedb3e1794d9"
Path: "/sitecore/templates/Project/app/Styleguide-ContentList-Item-Template/__Standard Values"
DB: master
SharedFields:
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{6C59AE29-D0A1-4B77-9305-0ABAB21D5FE5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190813T133628Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
