---
ID: "e9fa3975-76f0-5d7e-a92f-2eb8534cb97e"
Parent: "de434540-8942-51a0-bbde-4107fa418dd9"
Template: "de434540-8942-51a0-bbde-4107fa418dd9"
Path: "/sitecore/templates/Project/app/Styleguide-FieldUsage-Custom/__Standard Values"
DB: master
SharedFields:
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{6C59AE29-D0A1-4B77-9305-0ABAB21D5FE5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190813T133633Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
