---
ID: "d61ec43f-d5f9-5eac-af7e-6c8ce5d2e270"
Parent: "52acfa8c-9907-577f-8aa0-c52275589b29"
Template: "52acfa8c-9907-577f-8aa0-c52275589b29"
Path: "/sitecore/templates/Project/app/Styleguide-Layout-Tabs/__Standard Values"
DB: master
SharedFields:
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{6C59AE29-D0A1-4B77-9305-0ABAB21D5FE5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190813T133639Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
