---
ID: "976aec1f-d8cc-5d95-89c3-c1c551f38fbf"
Parent: "d5ec7395-aa0c-5660-948f-5f45847f45bc"
Template: "d5ec7395-aa0c-5660-948f-5f45847f45bc"
Path: "/sitecore/templates/Project/app/Styleguide-Tracking/__Standard Values"
DB: master
SharedFields:
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{6C59AE29-D0A1-4B77-9305-0ABAB21D5FE5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190813T133640Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
