---
ID: "d048ab9b-7438-48d1-aac9-cbd63125bbdb"
Parent: "14a80548-bafa-451b-8844-56170152d1cf"
Template: "14a80548-bafa-451b-8844-56170152d1cf"
Path: /sitecore/templates/Project/app/Product/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190814T181339Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
