---
ID: "e894fff9-ccbc-5fd1-9570-db32189074c0"
Parent: "d93fc44b-6bf3-5c4a-b58b-98995809a0ea"
Template: "d93fc44b-6bf3-5c4a-b58b-98995809a0ea"
Path: "/sitecore/templates/Project/app/Styleguide-Layout-Reuse/__Standard Values"
DB: master
SharedFields:
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{6C59AE29-D0A1-4B77-9305-0ABAB21D5FE5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190813T133638Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
